<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QREU.Domain\QREU.Domain.csproj" />
    <ProjectReference Include="..\QREU.Core\QREU.Core.csproj" />
    <ProjectReference Include="..\QREU.Writer\QREU.Writer.csproj" />
  </ItemGroup>

</Project>
