<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QREU.Domain\QREU.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data" Version="1.5.2" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
