name: BollingerBondsBreakout

instruments:
  - MSFT

factors:

startDate: 2000-01-01
endDate: 2030-01-01

strategy:
  type: BollingerBondsBreakout
  parameters:
    middleBandPeriod: 2000
    sideBandsPeriod: 2000
    standardDeviationMultiplier: 2
    source: close
