name: sample

instruments:
  - ORCL
  - MSFT

factors:
  
startDate: 2000-06-22
endDate: 2029-07-22

strategy:
  type: BBB
  parameters:
    middleperiod: 2500
    sideperiod: 2500
    stdm: 2
    source: close