name: sample

instruments:
  - MSFT

factors:
  - symbol: MSFT
    name: eps
  
startDate: 2000-01-01
endDate: 2030-01-01

strategy:
  type: BBB
  parameters:
    period: 5000
    sideperiod: 5000
    stdm: 2.5
    source: close