name: BollingerBondsBreakout

instruments:
  - EURUSD

factors:

startDate: 2000-01-01
endDate: 2029-01-01

strategy:
  type: BollingerBondsBreakout
  parameters:
    middleBandPeriod: 250
    sideBandsPeriod: 4755
    standardDeviationMultiplier: 2
    source: close
