name: sample

instruments:
  - MSFT
  - ORCL

factors:
  - symbol: MSFT
    name: eps
  
startDate: 2019-06-22
endDate: 2019-07-22

strategy:
  type: BBB
  parameters:
    period: 500
    sideperiod: 500
    stdm: 2.5
    source: close